### ISSUE TITLE
2FA generates illegal code

### ISSUE THREAD

**Issue by mzch** [Xyfir/accownt#2]
Enabling 2FS , I scanned Barcode using Google Authenticator, but failed.
Using some scanner can scan successfully but some failed.
And by entering secret-key different TOTP generate from scanned image.
Please fix this.

**Comment by MrXyfir** [comment]
The issue is probably with our two-factor authentication package, [speakeasy](https://www.npmjs.com/package/speakeasy), which unfortunately is very outdated. Maybe there is another package we could use?

**Comment by mzch** [comment]
How about [passport-2fa-totp](https://github.com/jaredhanson/passport)?

**Comment by MrXyfir** [comment]
I believe that requires Passport to be implemented first which would be a significant task.

**Comment by mzch** [comment]
See #4

**Comment by mzch** [comment]
Sorry, I forgot to add `NAME` to QR code label. See #5

**Comment by MrXyfir** [comment]
Thanks!
